name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"   # se actualiza diario
  workflow_dispatch:       # ejecutable a mano
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: jennifergc
          outputs: |
            dist/snake.svg
            dist/snake.gif
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
